### ISSUE TITLE
HTML Agility pack updates

### ISSUE THREAD

**Issue by adamtuliper** [OctopusDeploy/ICanHasDotnetCore#25]
Projects that use HTML Agility Pack show there's no .net core, though there is this:
https://www.nuget.org/packages/HtmlAgilityPack.NetCore/

**Comment by droyad** [comment]
@adamtuliper Unfortunately our tool isn't smart enough to figure out that that is the replacement package. However I've added a known replacement record, so that should show up in the future.

If you find any more, you can submit a PR with changes to https://github.com/OctopusDeploy/ICanHasDotnetCore/blob/master/source/Magic/NugetPackages/Data/KnownReplacements.json

Thanks :)
