### ISSUE TITLE
Q: What is the exact idea behind Option<T>

### ISSUE THREAD

**Issue by MiroslavMikus** [OctopusDeploy/ICanHasDotnetCore#34]
Hi, great repository. I was browsing the code and found the Option class. This look like 'value-safe' implementation fo the `Nullable<T>` struct. Could you provide some 'story behind'? 

Thank you in advice

**Comment by droyad** [comment]
@MiroslavMikus Sure. Yes you are right, it is like Nullable<T>. It is implementing the [option monad](https://en.wikipedia.org/wiki/Option_type) more or less. 

The idea behind it is mainly to highlight that a method may return `null` so that the caller is strongly encouraged to handled the `null` case. C# is [introducing this](https://blogs.msdn.microsoft.com/dotnet/2017/11/15/nullable-reference-types-in-csharp/) as a first class feature.

It also allows for the [railroad](https://fsharpforfunandprofit.com/posts/recipe-part2/) pattern (along with the `Result<T>` type). For [example](https://github.com/OctopusDeploy/ICanHasDotnetCore/blob/697003f7be0f76d2be7a8fa65895a1d2ef8b9ce4/source/Magic/NugetPackages/NugetPackageInfoRetriever.cs#L77) and this [example](https://github.com/OctopusDeploy/ICanHasDotnetCore/blob/697003f7be0f76d2be7a8fa65895a1d2ef8b9ce4/source/Magic/NugetPackages/NugetPackageInfoRetriever.cs#L92).
